# Generated by Django 2.2.19 on 2021-04-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0005_auto_20210412_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Village',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='gali',
            old_name='village',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='village',
            new_name='district',
        ),
    ]
