# Generated by Django 2.2.19 on 2021-04-12 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0006_auto_20210412_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gali',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='gali',
            new_name='city',
        ),
    ]
